def pappers_scrape_task(company_id: str, id_type):
    """
    Pappers scraping task to retrieve company information.

    :param company_id: The identification of the company to scrape data for.
    :param id_type: The type of ID (e.g. Name, SIREN, SIRET) to be used for scraping.
    :return: A formatted string with instructions for scraping Pappers.
    """

    return f"""Follow these steps to scrape the data:

    1. Go to https://www.pappers.fr/

    2. Locate the search bar and input the company's identifications: {company_id}, which is the company's {id_type}, then press Enter to initiate the search.

    3. From the search results, click on the first relevant result to access the company details.

    4. Once on the company page, extract and organize the information following this example:

        - **Informations juridiques de ...**:
            - SIREN: ...
            - SIRET: ...
            - Forme juridique: ...
            - Numéro de TVA: ...
            - Inscription au RCS: ...
            - Incripstion au RNE: ...
            - Numéro RCS: ...
            - Capital social: ...

        - **Activité de ...**:
            - Activité principale déclarée: ...
            - Code NAF ou APE: ...
            - Domaine d'activité: ...
            - Forme d'exercise: ...
            - Conventions collectives supposées: ...
            - Date de clôture d'exercice comptablr: ... (if available)

        - **Etablissement de l'entreprise ...**:
            - Type d'établissement: (example: Siège)
            - Statut: (example: En activité)
            - Adresse: ...
            - Date de création: ...

        - Finances de ... (if available):
            - Performance:
                - Annee XXXX:
                    - Chiffre d'affaires: ...
                    - Marge brute: ...
                    - EBITDA - EBE: ...
                    - Résultat d'exploitation: ...
                    - Résultat net: ...
                    - (Other financial metrics if available)
                
                - (Other years if available):

            - Croissance:
                - Annee XXXX:
                    - Taux de croissance du CA: ...
                    - Taux de marge brute: ...
                    - Taux de marge d'EBITDA: ...
                    - Taux de marge opérationnelle: ...

            - Gestion BFR:
                - Annee XXXX:
                    - BFR: ...

        - **Dirigeants et représentants de ...**:
            - Nom Complet: ...
            - Fonction: ...
            - Age/Date de naissance: ...
            
        - **Documents juridiques de...**:
            - Type de document: (example: Certificat, Statut constitutif, Extrait de procès-verbal, Inconnu, etc.)
            - Nom de document: ...
            - Date de document: ...
       
        - **Annonces BODACC de ...**: Include all BODACC announcements.

        - **Comptes annuels de ...**:
            - Nom du document: ...
            - Date de document: ...

            - Nom du document: ...
            - Date de document: ...

        - **Comment contacter ...**:
            - Téléphone: ...
            - Email: ...
            - Site internet: ...
            - Adresse complète: ...

        - **Entreprises citées de ...**:
            - Nom de l'entreprise/personne: ...
            - Nature supposée de la relation: ... (example: Notaire)


    5. If information for a section is unavailable or unparseable, skip that section and continue.

    Important Notes:
        - If the the information are a list for example "Dirigeants et représentants de ..." and "Documents juridiques de...", please format them as a list with bullet points.
        - If the section/card is scrollable, ensure to scroll to the bottom of the page to load all information before extracting data.

    The final output should be a well-organized, human-readable text document containing all of the extracted and organized information and indicate at the top of the document that the info is scraped from pappers.fr."""
